### ISSUE TITLE
The script breaks the contents in the "To" field on mail.disroot.org

### ISSUE THREAD

**Issue by RedSteel-1** [eight04/linkify-plus-plus#47]
I'm using the script, and it has an old issue:
It breaks the contents in the "To" field on mail.disroot.org, when the emails are entered in the field.
Steps:
1. Log in to Disroot mail and press "New message" button.
2. Enter some emails in the "To" field.
3. Press somewhere outside of the field and see the results.

Could this be fixed?

**Comment by eight04** [comment]
Is it just a styling issue or it makes disroot unable to send emails?

**Comment by eight04** [comment]
Just registered an account and tried sending an email. It seems that it is just a styling issue. If you have a custom CSS extension like Stylus, you can fix it via the following style:
```css
.linkifyplus {
  position: static;
}
```

**Comment by Agych** [comment]
> Is it just a styling issue or it makes disroot unable to send emails?

it's just styling


> Just registered an account and tried sending an email. It seems that it is just a styling issue. If you have a custom CSS extension like Stylus, you can fix it via the following style:

yes i can, even though it would require to do this in all 10 browsers i have in my 2 PCs,
the thing is that in this case some of my contacts using this email and having the script installed by me (in particular case), as welll as (in general) many people who might not even know what "css" and "extension" is, will have to do the same, which most likely they just won't


would it be possible to have it as an update in the script that everyone who have it installed will receive?

**Comment by eight04** [comment]
You mean to insert CSS in the script?

Actually, I always think these site-specific features are not good ideas.

1. It will be useful for disroot users, but it will be a useless feature for non-disroot users.
2. Besides maintaining a script that converts text to link, I also have to maintain css code for specific sites.

There was a similar request for travis: https://github.com/eight04/linkify-plus-plus/issues/15

However, since requests are low, maybe we can consider adding them to LPP...? IDK.

> yes i can, even though it would require to do this in all 10 browsers i have in my 2 PCs,

You may want to turn on sync in your script/style manager so you don't have to update all of them individually.

(You still have to turn on sync for each browser individually in case you haven't done this).

**Comment by Agych** [comment]
regarding sync:
me and many people I know don't use something so untrusted, especially for sensitive data,
in other words browser sync has always been a no-go and has never been in use
(moreover many browsers don't have sync)

what is LPP btw?

> It will be useful for disroot users, but it will be a useless feature for non-disroot users
If adding the fix to the script is done: the good for the former, doesn't matter for the latter,
if not: the bad for the former, still doesn't matter for the latter,
The choice between making a certain group of users happy or not, go for the former :P

**Comment by eight04** [comment]
> what is LPP btw?

Linkify Plus Plus

> if not: the bad for the former

Just want to point out that it is not bad for all of them. Only bad for people don't know how to fix it by CSS or by excluding the script.

**Comment by eight04** [comment]
It seems that Disroot updated their site and this is no longer an issue.
